{
  lib,
  python3Packages,
  fetchFromGitHub,
  librsvg,
  linkFarm,
  wrapGAppsHook3,
  gtk3,
  gobject-introspection,
  lightdm,
  lightdm-debathena-greeter,
  onboard,
}:

# Based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/li/lightdm-slick-greeter/package.nix
# Note that the package name is lightdm-debathena-greeter (to follow Nix conventions) but the files are called debathena-lightdm-greeter!
python3Packages.buildPythonApplication rec {
  pname = "lightdm-debathena-greeter";
  version = "1.13.3";
  src = fetchFromGitHub {
    owner = "mit-athena";
    repo = "lightdm-config";
    rev = version;
    hash = "sha256-M83qopIjN+skNK0z61qdbLftvVdLczP4oQZXoqya3UA=";
  };

  format = "other";

  nativeBuildInputs = [
    librsvg
    gobject-introspection
    wrapGAppsHook3
  ];

  buildInputs = [
    gtk3
    lightdm
    onboard
  ];

  propagatedBuildInputs = with python3Packages; [
    pygobject3
    dbus-python
  ];

  extraFiles = ../../img;
  postUnpack = ''
    rsvg-convert --zoom 0.4 "$extraFiles"/logo.svg -o source/debian/debathena.png
    for i in {1..8}
    do
      rsvg-convert --zoom 0.4 "$extraFiles"/logo$i.svg -o source/debian/debathena$i.png
    done
  '';

  patches = [
    ./python3.patch # Mostly generated by 2to3
  ];

  preConfigure = ''
    cd debian
  '';

  installPhase = ''
    mkdir -p $out/bin $out/etc $out/share/xgreeters $out/share/debathena-lightdm-greeter
    cp debathena-lightdm-greeter $out/bin
    cp debathena-lightdm-greeter.ini $out/etc
    cp debathena-lightdm-greeter.desktop $out/share/xgreeters
    cp debathena-lightdm-greeter.ui background.jpg debathena*.png $out/share/debathena-lightdm-greeter
    runHook postInstall
  '';

  postInstall = ''
    substituteInPlace $out/etc/debathena-lightdm-greeter.ini \
      --replace-fail /usr/share/debathena-lightdm-config $out/share/debathena-lightdm-greeter
    substituteInPlace $out/bin/debathena-lightdm-greeter \
      --replace-fail /usr/share/debathena-lightdm-config $out/share/debathena-lightdm-greeter \
      --replace-fail /etc/debathena-lightdm-greeter.ini $out/etc/debathena-lightdm-greeter.ini \
      --replace-fail /usr/bin/onboard ${onboard}/bin/onboard
    substituteInPlace $out/share/xgreeters/debathena-lightdm-greeter.desktop \
      --replace-fail Exec=/usr/lib/debathena-lightdm-config/debathena-lightdm-greeter Exec=$out/bin/debathena-lightdm-greeter
  '';

  passthru.xgreeters = linkFarm "debathena-greeter-xgreeters" [
    {
      path = "${lightdm-debathena-greeter}/share/xgreeters/debathena-lightdm-greeter.desktop";
      name = "debathena-lightdm-greeter.desktop";
    }
  ];

  meta = {
    description = "LightDM greeter for Debathena";
    homepage = "https://github.com/mit-athena/lightdm-config";
    platforms = lib.platforms.linux;
    license = lib.licenses.mit;
  };
}
