{
  lib,
  python3,
  python3Packages,
  fetchFromGitHub,
  linkFarm,
  wrapGAppsHook3,
  gtk3,
  gobject-introspection,
  lightdm,
  lightdm-debathena-greeter,
}:

# Based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/li/lightdm-slick-greeter/package.nix
# Note that the package name is lightdm-debathena-greeter (to follow Nix conventions) but the files are called debathena-lightdm-greeter!
python3Packages.buildPythonApplication rec {
  pname = "lightdm-debathena-greeter";
  version = "1.13.3";
  src = fetchFromGitHub {
    owner = "mit-athena";
    repo = "lightdm-config";
    rev = version;
    hash = "sha256-M83qopIjN+skNK0z61qdbLftvVdLczP4oQZXoqya3UA=";
  };

  format = "other";

  nativeBuildInputs = [
    gobject-introspection
    wrapGAppsHook3
  ];

  buildInputs = [
    gtk3
    lightdm
  ];

  propagatedBuildInputs = with python3Packages; [
    pygobject3
    dbus-python
  ];

  patches = [
    ./python3.patch # Generated by 2to3
  ];

  preConfigure = ''
    cd debian
  '';

  # This is gross
  installPhase = ''
    mkdir -p $out/bin $out/etc $out/share/xgreeters $out/share/debathena-lightdm-greeter
    cp debathena-lightdm-greeter $out/bin
    cp debathena-lightdm-greeter.ini $out/etc
    cp debathena-lightdm-greeter.desktop $out/share/xgreeters
    cp debathena-lightdm-greeter.ui background.jpg debathena*.png $out/share/debathena-lightdm-greeter
    substituteInPlace "$out/etc/debathena-lightdm-greeter.ini" \
      --replace-fail "/usr/share/debathena-lightdm-config" "$out/share/debathena-lightdm-greeter"
    substituteInPlace "$out/bin/debathena-lightdm-greeter" \
      --replace-fail "/usr/share/debathena-lightdm-config" "$out/share/debathena-lightdm-greeter" \
      --replace-fail "/etc/debathena-lightdm-greeter.ini" "$out/etc/debathena-lightdm-greeter.ini"
    substituteInPlace "$out/share/xgreeters/debathena-lightdm-greeter.desktop" \
      --replace-fail "Exec=/usr/lib/debathena-lightdm-config/debathena-lightdm-greeter" "Exec=$out/bin/debathena-lightdm-greeter"
  '';

  passthru.xgreeters = linkFarm "debathena-greeter-xgreeters" [
    {
      path = "${lightdm-debathena-greeter}/share/xgreeters/debathena-lightdm-greeter.desktop";
      name = "debathena-lightdm-greeter.desktop";
    }
  ];

  meta = {
    description = "LightDM greeter for Debathena";
    homepage = "https://github.com/mit-athena/lightdm-config";
    platforms = lib.platforms.linux;
  };
}
