{
  stdenv,
  lib,
  fetchurl,
  pkg-config,
  makeWrapper,
  autoreconfHook,
  krb5,
  ncurses,
  openssl,
  glib,
  perl,
  zip,
  which,
  libxcrypt,
  zephyr,
  libkrb5-e2fs,
  perlPackages,
}:

let
  # Autogenerated by https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/nix-generate-from-cpan.pl
  PAR = with perlPackages; buildPerlPackage {
    pname = "PAR";
    version = "1.021";
    src = fetchurl {
      url = "mirror://cpan/authors/id/R/RS/RSCHUPP/PAR-1.021.tar.gz";
      hash = "sha256-cy/P08G6i7MU19+S0UIJ4GbRm0xF+EUeWNaE8N3+a/M=";
    };
    propagatedBuildInputs = [
      ArchiveZip
      PARDist
    ];
    meta = {
      description = "Perl Archive Toolkit";
      license = with lib.licenses; [
        artistic1
        gpl1Plus
      ];
    };
  };
  MIMEBase64URLSafe = with perlPackages; buildPerlPackage {
    pname = "MIME-Base64-URLSafe";
    version = "0.01";
    src = fetchurl {
      url = "mirror://cpan/authors/id/K/KA/KAZUHO/MIME-Base64-URLSafe-0.01.tar.gz";
      hash = "sha256-y5lmxQU4u2dqtnvECnyEEBmyO6IkPQ/8wszwhOXDN5g=";
    };
  };
  Ouch = with perlPackages; buildPerlPackage {
    pname = "Ouch";
    version = "0.0501";
    src = fetchurl {
      url = "mirror://cpan/authors/id/R/RI/RIZEN/Ouch-0.0501.tar.gz";
      hash = "sha256-Ztxrle0nhr5EqxKdqfSkzo4eMy+DEqJoeiOtijgA7/Q=";
    };
    propagatedBuildInputs = [ TestTrap ];
    meta = {
      description = "Exceptions that don't hurt";
      license = with lib.licenses; [ artistic1 gpl1Plus ];
    };
  };
  URIEncode = with perlPackages; buildPerlPackage {
    pname = "URI-Encode";
    version = "1.1.1";
    src = fetchurl {
      url = "mirror://cpan/authors/id/M/MI/MITHUN/URI-Encode-v1.1.1.tar.gz";
      hash = "sha256-S7nOTnAWwBOM+cI3VQhZUobvocjcFbRbqkxHKBwIJDs=";
    };
    meta = {
      homepage = "https://github.com/mithun/perl-uri-encode";
      description = "Simple percent Encoding/Decoding";
      license = with lib.licenses; [ artistic1 gpl1Plus ];
    };
  };
  # End of autogenerated stuff
  # Yes, I made this list by repeatedly building and running BarnOwl until the errors went away
  perlDeps = with perlPackages; [
    AnyEvent
    ClassAccessor
    ExtUtilsDepends
    Glib
    ModuleInstall
    PAR
    JSON
    NetTwitterLite
    AnyEventIRC
    AnyMoose
    AuthenSASL
    NetDNS
    MIMEBase64URLSafe
    Ouch
    AnyEventHTTP
    URIEncode
    DateTime
    DateTimeFormatStrptime
    TextAutoformat
  ];
in
stdenv.mkDerivation (finalAttrs: {
  pname = "barnowl";
  version = "1.11-master-1f65aee";

  src = fetchurl {
    url = "https://github.com/barnowl/barnowl/archive/1f65aee2011f5e938da110a9dcfe741b0a7c1d03.tar.gz";
    hash = "sha256-S5oONvaDhleCPcupgLxCdeJOXhOYLYu8Z3meBXcjZL0=";
  };

  nativeBuildInputs = [
    pkg-config
    makeWrapper
  ];
  buildInputs = [
    autoreconfHook
    krb5
    ncurses
    openssl
    glib
    (perl.withPackages (ps: perlDeps))
    zip
    which
    libxcrypt
    zephyr
    libkrb5-e2fs
  ];

  # This is super gross
  postPatch = ''
    cat <<'EOF' > perl/lib/FixFind.pm
    package FixFind;
    use strict;
    use warnings;
    use File::Find ();

    my $orig_find = \&File::Find::find;

    no warnings 'redefine';
    *File::Find::find = sub {
        my ($arg, @dirs) = @_;
        if (ref $arg eq 'HASH') {
            $arg->{follow} = 1;
            $arg->{follow_skip} = 2;
        }
        $orig_find->($arg, @dirs);
    };

    1;
    EOF

    substituteInPlace perl/modules/Makefile.am \
      --replace-fail 'BARNOWL_PERL := $(shell which perl) -I$(abs_srcdir)/../lib' 'BARNOWL_PERL := $(shell which perl) -I. -I$(abs_srcdir)/../lib -MFixFind'
  '';

  postFixup = ''
    wrapProgram $out/bin/barnowl \
      --prefix PERL5LIB : "${perlPackages.makeFullPerlPath perlDeps}"
  '';

  meta = {
    homepage = "https://barnowl.mit.edu/";
    description = "A multi-protocol curses IM client";
    platforms = lib.platforms.linux;
    license = lib.licenses.gpl2;
  };
})
